export const defaultDestinations = [
  {
    name: 'Kashmir',
    country: 'India',
    state: 'Jammu & Kashmir',
    description:
      'Revered as "Paradise on Earth", Kashmir offers an ethereal canvas of serene mirrored lakes, hand-carved wooden shikaras, snow-draped alpine peaks, and century-old saffron and walnut orchards. Experience the gentle rhythm of water and mountain solace.',
    shortDescription: 'Mirror-still lakes, alpine pine valleys, and timeless Himalayan serenity.',
    category: 'Mountains',
    bannerImage: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1600&q=80',
    images: [
      'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=1200&q=80',
    ],
    modelUrl: '/models/kashmir_scene.glb',
    panoramaUrl: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=2400&q=80',
    attractions: [
      {
        name: 'Dal Lake & Floating Market',
        description: 'Iconic freshwater lake famous for colorful hand-carved cedar Shikaras and dawn floating flower markets.',
        image: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [0, 1.2, -4],
        tags: ['Serene', 'Water', 'Heritage'],
      },
      {
        name: 'Gulmarg Meadow of Flowers',
        description: 'Vast alpine meadow framed by Mount Apharwat, renowned for the world-class high-altitude gondola.',
        image: 'https://images.unsplash.com/photo-1598091383021-15ddea10925d?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [-3.5, 1.5, -2],
        tags: ['Snow', 'Meadows', 'Adventure'],
      },
      {
        name: 'Pari Mahal & Shalimar Bagh',
        description: 'Royal Mughal terraced gardens overlooking Srinagar, with seven tiered terraces and natural spring fountains.',
        image: 'https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [3.5, 1.3, -3],
        tags: ['Architecture', 'Gardens', 'History'],
      },
    ],
    activities: [
      {
        id: 'kash-act-1',
        title: 'Virtual Shikara Glide',
        description: 'Steer a traditional wooden shikara boat across tranquil waters while listening to soulful Santoor tunes.',
        type: 'exploration',
        xpReward: 100,
        duration: '10 mins',
        difficulty: 'Easy',
      },
      {
        id: 'kash-act-2',
        title: 'Kashmir Cultural Knowledge Quest',
        description: 'Test your understanding of Kashmiri arts, Pashmina weaving, and Mughal garden architecture.',
        type: 'quiz',
        xpReward: 80,
        duration: '5 mins',
        difficulty: 'Medium',
      },
      {
        id: 'kash-act-3',
        title: 'Golden Sunset Memory Snap',
        description: 'Frame and capture high-resolution scenic panoramas of the sunset reflecting off Dal Lake.',
        type: 'photo',
        xpReward: 60,
        duration: '3 mins',
        difficulty: 'Easy',
      },
    ],
    culture: {
      traditions: 'Celebrated for Kashmiri hospitality (Mehmaan-nawazi), hand-knotted silk carpets, and papier-mâché artistry.',
      etiquette: 'Warm greetings with "Adaab" or "Salam", modest attire in heritage zones, and respect for prayer sanctums.',
      language: 'Kashmiri, Urdu, Hindi, English',
      festivals: ['Tulip Festival (Spring)', 'Shikara Festival', 'Saffron Harvest (Autumn)'],
    },
    food: [
      { name: 'Kashmiri Kahwa', description: 'Fragrant green tea brewed with whole saffron, crushed green cardamoms, and almond slivers.', veg: true, iconic: true },
      { name: 'Dum Olav', description: 'Tender baby potatoes slow-cooked in a velvety aromatic yogurt and fennel seed gravy.', veg: true, iconic: true },
      { name: 'Nadru Yakhni', description: 'Lotus stems harvested straight from Dal Lake simmered gently in spiced curd broth.', veg: true, iconic: true },
      { name: 'Rogan Josh', description: 'Traditional aromatic meat dish colored naturally with Kashmiri chili and mawal flower petals.', veg: false, iconic: true },
    ],
    accessibility: {
      wheelchairAccessible: true,
      mobilityRating: 4,
      audioSupportAvailable: true,
      terrainDifficulty: 'Easy',
      notes: [
        'Boardwalks along Boulevard Road feature gentle ramps.',
        'Virtual low-motion mode completely eliminates boat tilt sensations.',
        'High contrast audio narration and descriptive subtitles enabled.',
      ],
    },
    coordinates: { lat: 34.0837, lng: 74.7973 },
    featured: true,
    simulationDefaults: {
      avgHotelPrice: 95,
      avgDailyBudget: 60,
      bestSeason: 'April - October (Tulips & Autumn Colors)',
      peakCrowdMonths: ['May', 'June', 'December'],
    },
  },
  {
    name: 'Goa',
    country: 'India',
    state: 'Goa',
    description:
      'A sun-kissed coastal sanctuary where golden Arabian Sea shores blend seamlessly with centuries of Portuguese colonial architecture, vibrant spice plantations, and the relaxed philosophy of "susegad".',
    shortDescription: 'Golden sands, turquoise waters, colonial Latin quarters, and coastal serenity.',
    category: 'Beaches',
    bannerImage: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1600&q=80',
    images: [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: [
      {
        name: 'Palolem Crescent Beach',
        description: 'Tranquil sheltered bay fringed with towering coconut palms, gentle breaks, and dolphin spotting.',
        image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [0, 1.2, -4],
      },
      {
        name: 'Fontainhas Heritage Quarter',
        description: 'Asia’s largest Latin Quarter, filled with pastel yellow and cobalt blue Portuguese mansions from the 18th century.',
        image: 'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [-3.5, 1.5, -2],
      },
      {
        name: 'Basilica of Bom Jesus',
        description: 'UNESCO World Heritage baroque monument holding the sacred mortal remains of St. Francis Xavier.',
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [3.5, 1.3, -3],
      },
    ],
    activities: [
      {
        id: 'goa-act-1',
        title: 'Fontainhas Architectural Stroll',
        description: 'Inspect wrought iron balconies, azulejo ceramic tiles, and colonial archways.',
        type: 'cultural',
        xpReward: 90,
        duration: '8 mins',
        difficulty: 'Easy',
      },
      {
        id: 'goa-act-2',
        title: 'Coastal Sunset Harmony',
        description: 'Relax to ambient ocean wave physics and capture coastal memories.',
        type: 'photo',
        xpReward: 60,
        duration: '5 mins',
        difficulty: 'Easy',
      },
    ],
    culture: {
      traditions: 'Celebration of susegad (contented leisurely pace of life), Konkani music, and beach community gatherings.',
      etiquette: 'Beachwear appropriate on sands; modest attire requested when visiting historic cathedrals and temples.',
      language: 'Konkani, English, Hindi, Portuguese',
      festivals: ['Goa Carnival (Feb)', 'Sao Joao Water Festival (June)', 'Sunburn & Winter Fest (Dec)'],
    },
    food: [
      { name: 'Bebinca', description: 'Legendary seven-layered Goan dessert made with coconut milk, egg yolk, and nutmeg.', veg: true, iconic: true },
      { name: 'Goan Fish Curry & Rice', description: 'Fresh catch simmered in rich coconut gravy infused with tangy local kokum.', veg: false, iconic: true },
      { name: 'Khatkhate Stew', description: 'Nutritious festive mixed vegetable stew with lentils, coconut, and tefla berries.', veg: true, iconic: true },
    ],
    accessibility: {
      wheelchairAccessible: true,
      mobilityRating: 4,
      audioSupportAvailable: true,
      terrainDifficulty: 'Easy',
      notes: ['Flat coastal walkways and accessible beach ramps installed in major zones.'],
    },
    coordinates: { lat: 15.2993, lng: 74.124 },
    featured: true,
    simulationDefaults: {
      avgHotelPrice: 85,
      avgDailyBudget: 55,
      bestSeason: 'November - February',
      peakCrowdMonths: ['December', 'January'],
    },
  },
  {
    name: 'Konark',
    country: 'India',
    state: 'Odisha',
    description:
      'Home to the majestic 13th-century Sun Temple, a UNESCO World Heritage marvel conceived as the grand chariot of Surya. Marvel at 24 monumental stone wheels intricately sculpted with cosmic calendars.',
    shortDescription: 'Colossal stone chariot of the Sun God, astronomical sundials, and Kalinga heritage.',
    category: 'Heritage',
    bannerImage: 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=1600&q=80',
    images: [
      'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1628102491328-971a93bdf483?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: [
      {
        name: 'The Great Sun Chariot Wheels',
        description: '24 stone wheels functioning as remarkably accurate solar clocks based on shadows cast by the axle.',
        image: 'https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [0, 1.2, -4],
      },
      {
        name: 'Natya Mandap (Dancing Hall)',
        description: 'Pillared open hall where ancient Odissi dancers performed, every pillar carved with 128 traditional postures.',
        image: 'https://images.unsplash.com/photo-1628102491328-971a93bdf483?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [-3, 1.5, -2],
      },
      {
        name: 'Chandrabhaga Clean Beach',
        description: 'Pristine Blue Flag certified beach where holy dawn prayers greet the rising sun.',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [3, 1.2, -3],
      },
    ],
    activities: [
      {
        id: 'kon-act-1',
        title: 'Sun Wheel Sundial Decoding',
        description: 'Read the time of day by aligning shadows on the ancient spokes of the Surya Chariot.',
        type: 'mini-game',
        xpReward: 120,
        duration: '7 mins',
        difficulty: 'Medium',
      },
      {
        id: 'kon-act-2',
        title: 'Odissi Sculptural Pose Match',
        description: 'Discover the meaning behind classical temple dance mudras sculpted in stone.',
        type: 'cultural',
        xpReward: 80,
        duration: '6 mins',
        difficulty: 'Easy',
      },
    ],
    culture: {
      traditions: 'Origin center of classical Odissi dance, silver filigree craft (Tarakasi), and Pattachitra cloth paintings.',
      etiquette: 'Remove footwear before entering temple sanctuaries, maintain quiet reverent demeanor around sacred stones.',
      language: 'Odia, Hindi, English',
      festivals: ['Konark Dance Festival (Dec 1-5)', 'Magha Saptami Sun Festival (Jan/Feb)'],
    },
    food: [
      { name: 'Chhena Poda', description: 'Known as the "Indian Cheesecake", cottage cheese caramelized with cardamom and jaggery.', veg: true, iconic: true },
      { name: 'Dalma', description: 'Wholesome split chickpea stew infused with raw papaya, pumpkin, and roasted cumin.', veg: true, iconic: true },
      { name: 'Khaja Pastry', description: 'Crispy layered sweet pastry prepared according to sacred temple traditions.', veg: true, iconic: true },
    ],
    accessibility: {
      wheelchairAccessible: true,
      mobilityRating: 4,
      audioSupportAvailable: true,
      terrainDifficulty: 'Moderate',
      notes: [
        'ASI paved stone pathways around temple perimeter suitable for wheelchairs.',
        '3D tactile preview and high-contrast zoom enabled for intricate carvings.',
      ],
    },
    coordinates: { lat: 19.8876, lng: 86.0945 },
    featured: true,
    simulationDefaults: {
      avgHotelPrice: 65,
      avgDailyBudget: 40,
      bestSeason: 'October - March',
      peakCrowdMonths: ['December', 'January'],
    },
  },
  {
    name: 'Rajasthan',
    country: 'India',
    state: 'Rajasthan',
    description:
      'The timeless realm of Maharajas, where golden desert sands meet hilltop fortresses, palace courtyards with peacock mosaics, royal camel caravans, and vibrant folk rhythms of the desert wind.',
    shortDescription: 'Royal hilltop forts, desert palaces, camel caravans, and vibrant folklore.',
    category: 'Heritage',
    bannerImage: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1600&q=80',
    images: [
      'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: [
      {
        name: 'Amber Palace & Sheesh Mahal',
        description: 'Imposing Rajput-Mughal fortress overlooking Maota Lake, famous for its hall of mirrors where one candle illuminates the room.',
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [0, 1.2, -4],
      },
      {
        name: 'Thar Desert Sam Sand Dunes',
        description: 'Rolling golden sand waves where sunset turns the horizon crimson, followed by starlit acoustic folk performances.',
        image: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [-3.5, 1.4, -2],
      },
      {
        name: 'Hawa Mahal (Palace of Winds)',
        description: 'Five-story pink sandstone honeycomb facade with 953 ornate latticed windows designed to channel cool air.',
        image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [3.5, 1.2, -3],
      },
    ],
    activities: [
      {
        id: 'raj-act-1',
        title: 'Sheesh Mahal Mirror Chamber Quest',
        description: 'Rotate virtual light sources across thousands of Belgian mirrors to illuminate hidden royal insignias.',
        type: 'mini-game',
        xpReward: 110,
        duration: '8 mins',
        difficulty: 'Medium',
      },
      {
        id: 'raj-act-2',
        title: 'Desert Folk Melody Encounter',
        description: 'Listen to the desert Sarangi instrument and decipher ancient balladic tales.',
        type: 'cultural',
        xpReward: 75,
        duration: '6 mins',
        difficulty: 'Easy',
      },
    ],
    culture: {
      traditions: 'Legendary "Padharo Mhare Desh" welcome, vibrant tie-dye Bandhani textiles, blue pottery, and Kalbelia folk dance.',
      etiquette: 'Accepting offerings with both hands, removing shoes at temples and royal palace sanctums.',
      language: 'Hindi, Rajasthani, Marwari, English',
      festivals: ['Pushkar Camel Fair (Nov)', 'Desert Festival Jaisalmer (Feb)', 'Teej Festival'],
    },
    food: [
      { name: 'Dal Baati Churma', description: 'Baked wheat flour dumplings paired with spiced five-lentil curry and sweet jaggery crush.', veg: true, iconic: true },
      { name: 'Gatte ki Sabzi', description: 'Gram flour dumplings simmered in rich spiced curd gravy infused with asafoetida.', veg: true, iconic: true },
      { name: 'Ker Sangri', description: 'Authentic desert delicacy prepared from wild beans and berries dried under desert sun.', veg: true, iconic: true },
    ],
    accessibility: {
      wheelchairAccessible: true,
      mobilityRating: 3,
      audioSupportAvailable: true,
      terrainDifficulty: 'Moderate',
      notes: [
        'Electric golf carts and golf cart shuttles available in palace courtyards.',
        'Virtual tour includes step-free teleportation throughout fort ramparts.',
      ],
    },
    coordinates: { lat: 26.9124, lng: 75.7873 },
    featured: true,
    simulationDefaults: {
      avgHotelPrice: 110,
      avgDailyBudget: 70,
      bestSeason: 'October - March',
      peakCrowdMonths: ['November', 'December', 'January'],
    },
  },
  {
    name: 'Kerala',
    country: 'India',
    state: 'Kerala',
    description:
      'Known as "God\'s Own Country", Kerala is an emerald haven of labyrinthine palm-fringed backwaters, misty mountain spice hills in Munnar, Ayurvedic rejuvenation sanctuaries, and ancient Kathakali performing arts.',
    shortDescription: 'Emerald backwaters, kettuvallam houseboats, fragrant spice hills, and Ayurveda.',
    category: 'Nature',
    bannerImage: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1600&q=80',
    images: [
      'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: [
      {
        name: 'Alleppey Backwaters & Canal Network',
        description: 'Vast calm waterways where traditional thatched kettuvallam houseboats drift gently under palm canopies.',
        image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [0, 1.2, -4],
      },
      {
        name: 'Munnar Tea Plantations',
        description: 'Endless rolling hills cloaked in velvet green tea shrubs, morning mist, and endangered Nilgiri Tahr mountain goats.',
        image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [-3.5, 1.4, -2],
      },
      {
        name: 'Fort Kochi Chinese Fishing Nets',
        description: 'Cantilevered giant wooden shore-operated fishing nets set up by 14th-century Chinese traders against harbor sunsets.',
        image: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [3.5, 1.2, -3],
      },
    ],
    activities: [
      {
        id: 'ker-act-1',
        title: 'Backwater Houseboat Captain',
        description: 'Navigate a slow wooden houseboat through village canals with kingfishers and water lilies.',
        type: 'exploration',
        xpReward: 95,
        duration: '10 mins',
        difficulty: 'Easy',
      },
      {
        id: 'ker-act-2',
        title: 'Kathakali Mask & Emotion Guide',
        description: 'Identify the 9 classic facial emotional expressions (Navarasas) used in Kathakali dance.',
        type: 'cultural',
        xpReward: 85,
        duration: '6 mins',
        difficulty: 'Medium',
      },
    ],
    culture: {
      traditions: 'Centuries of classical Kathakali dance-drama, Kalaripayattu martial arts, and holistic Ayurvedic medicine.',
      etiquette: 'Comfortable cotton wear, traditional greeting with palms together "Namaskaram", eco-friendly practices in backwaters.',
      language: 'Malayalam, English, Tamil, Hindi',
      festivals: ['Onam Harvest Festival (Aug/Sep)', 'Vishu', 'Nehru Trophy Snake Boat Race'],
    },
    food: [
      { name: 'Appam with Vegetable Stew', description: 'Crisp-edged fluffy fermented rice pancakes served with coconut milk aromatic stew.', veg: true, iconic: true },
      { name: 'Kerala Sadya Feast', description: 'Over 24 vegetarian delicacies served gracefully on a fresh banana leaf during Onam.', veg: true, iconic: true },
      { name: 'Avial', description: 'Thick melange of 13 local vegetables, grated coconut, and curry leaves in fragrant coconut oil.', veg: true, iconic: true },
    ],
    accessibility: {
      wheelchairAccessible: true,
      mobilityRating: 4,
      audioSupportAvailable: true,
      terrainDifficulty: 'Easy',
      notes: [
        'Modern backwater houseboats feature step-free boarding ramps and wide doorways.',
        'Sensory-friendly audio mode with rain and birdsong ambiance.',
      ],
    },
    coordinates: { lat: 9.9312, lng: 76.2673 },
    featured: true,
    simulationDefaults: {
      avgHotelPrice: 90,
      avgDailyBudget: 55,
      bestSeason: 'September - March',
      peakCrowdMonths: ['December', 'January', 'August'],
    },
  },
  {
    name: 'Ladakh',
    country: 'India',
    state: 'Ladakh',
    description:
      'The "Land of High Passes" is a surreal cold desert plateau towering 3,500 meters above sea level. Featuring indigo skies, turquoise glacial lakes like Pangong Tso, Buddhist monasteries perched on craggy pinnacles, and star-studded midnight galaxies.',
    shortDescription: 'High-altitude cold desert, Buddhist monasteries, cobalt blue lakes, and stellar night skies.',
    category: 'Adventure',
    bannerImage: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1600&q=80',
    images: [
      'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?auto=format&fit=crop&w=1200&q=80',
    ],
    attractions: [
      {
        name: 'Pangong Tso Alpine Lake',
        description: 'Endorheic salt lake at 4,350 meters changing shades from brilliant turquoise to deep violet under shifting sunlight.',
        image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [0, 1.2, -4],
      },
      {
        name: 'Thiksey Cliffside Monastery',
        description: 'Twelve-story tiered Tibetan Buddhist complex resembling Lhasa’s Potala Palace, housing a 15m Maitreya Buddha statue.',
        image: 'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [-3.5, 1.5, -2],
      },
      {
        name: 'Khardung La Pass Viewpoint',
        description: 'Legendary mountain pass at 5,359 meters connecting the Indus valley to the Nubra Valley sand dunes.',
        image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
        hotspotPosition: [3.5, 1.2, -3],
      },
    ],
    activities: [
      {
        id: 'lad-act-1',
        title: 'Virtual Stargazing at Hanle Observatory',
        description: 'Identify celestial constellations in one of the world’s clearest Dark Sky Sanctuaries.',
        type: 'exploration',
        xpReward: 125,
        duration: '8 mins',
        difficulty: 'Medium',
      },
      {
        id: 'lad-act-2',
        title: 'Tibetan Prayer Wheel Spin',
        description: 'Spin hand-carved copper prayer wheels clockwise while meditating on ancient mantras.',
        type: 'cultural',
        xpReward: 70,
        duration: '4 mins',
        difficulty: 'Easy',
      },
    ],
    culture: {
      traditions: 'Vibrant monastic mask dances (Cham), prayer flags fluttering across windy passes, and sustainable mountain stewardship.',
      etiquette: 'Walk clockwise around chortens and monasteries, request permission before photographing monks and interiors.',
      language: 'Ladakhi (Bhoti), Tibetan, Hindi, English',
      festivals: ['Hemis Festival (June/July)', 'Ladakh Festival (Sept)', 'Losar New Year'],
    },
    food: [
      { name: 'Thukpa Noodle Soup', description: 'Steaming comforting noodle soup with fresh mountain vegetables and mild aromatic herbs.', veg: true, iconic: true },
      { name: 'Momos with Chutney', description: 'Steamed delicate dumplings filled with finely chopped cabbage, carrots, and wild herbs.', veg: true, iconic: true },
      { name: 'Butter Tea (Gur Gur Chai)', description: 'Traditional salty churning tea made with yak butter, salt, and black tea leaves.', veg: true, iconic: true },
    ],
    accessibility: {
      wheelchairAccessible: true,
      mobilityRating: 3,
      audioSupportAvailable: true,
      terrainDifficulty: 'Challenging',
      notes: [
        'Physical travel requires high-altitude acclimatization, making TravelTwin’s virtual visit the perfect accessible substitute for seniors or individuals with respiratory conditions.',
        'Full smooth virtual locomotion with zero altitude strain.',
      ],
    },
    coordinates: { lat: 34.1526, lng: 77.5771 },
    featured: true,
    simulationDefaults: {
      avgHotelPrice: 105,
      avgDailyBudget: 65,
      bestSeason: 'June - September',
      peakCrowdMonths: ['July', 'August'],
    },
  },
];
